//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_6_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumosHabitacion
    {
        public int ConsumoID { get; set; }
        public Nullable<int> HabitacionID { get; set; }
        public Nullable<System.DateTime> FechaConsumo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> MontoDecimal { get; set; }
    
        public virtual Habitaciones Habitaciones { get; set; }
    }
}
