//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_6_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosVacacionale
    {
        public string Documento { get; set; }
        public string NombreDocente { get; set; }
        public int CantidadCursos { get; set; }
        public double PorcentajeDescuento { get; set; }
        public int ValorPagoAntesDcto { get; set; }
        public int ValorDescuento { get; set; }
        public int TotalPagar { get; set; }
    }
}
