//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_6_8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDBEntities : DbContext
    {
        public HotelDBEntities()
            : base("name=HotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckIn> CheckIn { get; set; }
        public virtual DbSet<CheckOut> CheckOut { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ComentariosResenas> ComentariosResenas { get; set; }
        public virtual DbSet<Conferencias> Conferencias { get; set; }
        public virtual DbSet<ConsumosHabitacion> ConsumosHabitacion { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<Facturacion> Facturacion { get; set; }
        public virtual DbSet<Habitaciones> Habitaciones { get; set; }
        public virtual DbSet<MantenimientoHabitaciones> MantenimientoHabitaciones { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<ReservacionesEventos> ReservacionesEventos { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
    }
}
