//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_6_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaEscenarios
    {
        public string Documento { get; set; }
        public string Nombre { get; set; }
        public int HorasReserva { get; set; }
        public string DiaReserva { get; set; }
        public int ValorSinDescuento { get; set; }
        public int ValorDescuento { get; set; }
        public int ValorPagar { get; set; }
    }
}
